### PR TITLE
Make insecure detection work again.

### LINKED ISSUE #24: False positives
https://addons.thunderbird.net/en-US/thunderbird/addon/paranoia/reviews/1156471/

```
Sorry, but this plugins seems to guess TLS connections to be active.
I checked my actual/ old emails with faces (which are hard to differentiate) and their popup information and many emails without TLS notification in headers between mail servers were still marked as "Perfect - no known email providers and encryption between all hops" ???
Like this not too old email where you can yourself also subscribe/verify this behavior:

Received: from mail7.atl51.rsgsv.net ([205.201.135.7]) by mx-ha.gmx.net
(mxgmx011 [212.227.15.9]) with ESMTP (Nemesis) id 0LzGiX-1ffutS1fov-014QEI
for <...@gmx.de>; Wed, 10 Oct 2018 21:14:15 +0200
Received: from mail7.atl51.rsgsv.net ([205.201.135.7]) by mx-ha.gmx.net
(mxgmx011 [212.227.15.9]) with ESMTP (Nemesis) id 0LzGiX-1ffutS1fov-014QEI
for <...@gmx.de>; Wed, 10 Oct 2018 21:14:15 +0200
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; s=k1; d=divx.com;
h=Subject:From:Reply-To:To:Date:Message-ID:List-ID:List-Unsubscribe:
Content-Type:MIME-Version; i=feedback@divx.com;
bh=hKFncKmjznI7eWjYuebk14QtFUlkgSq0GCHGsM0zGWo=;
b=vr0HxyIJQVxudic78n62DFvEHXSnDXTtCKKYj8/EnmybQU5DhkVSqAh6hFiYL41LBM3LyRM219E1
4DrO4kVNxGqThmurSW1dmNvbW2rCMRMJm38l/rVeyfrHAuyD2pteJfeihRsmi0U9cfSFQYaubAQT
g2hcJZGQOMPq2HeYEEI=
Received: from (127.0.0.1) by mail7.atl51.rsgsv.net id hnp7oe2ddl4t for <...@gmx.de>; Wed, 10 Oct 2018 17:08:37 +0000 (envelope-from <bounce-mc.us18_93722225.221041-...=gmx.de@mail7.atl51.rsgsv.net>)
Subject: =?utf-8?Q?Thank=20you=20=2D=2D=20get=2025%=20off=20DivX=20Pro=21=C2=A0?=
From: =?utf-8?Q?DivX=20News?= <feedback@divx.com>
Reply-To: =?utf-8?Q?DivX=20News?= <feedback@divx.com>


=> ESMTP usage isn't ESMTPS (or some TLS written headers)
=> DKIM signature is no encryption - only origin proove !
```

### PR DESCRIPTION
**Pull request by sdellenb**
See https://github.com/gjedeer/paranoia/issues/24#issuecomment-538395987

Fixes #24

image

### CODE REVIEW

**Comment by sdellenb** [comment]
It's not working.. Will need to test some more (and bump the version).

**Comment by sdellenb** [comment]
@gjedeer The code was correct, but apparently, the missing version bump confused Thunderbird and it was not correctly updating. Bumped version and tested, and it's working again as expected.

**Comment by sdellenb** [comment]
I've been running the corrected version in TB 68 (locally versioned 0.3.1) for two weeks on macOS Mojave and Windows 10 and haven't encountered any issues.
If anyone else can test it, that would be awesome:
https://www.dropbox.com/s/3ip9jiz9epxzdbm/paranoia-0.3.1.xpi?dl=0

**Comment by gjedeer** [comment]
Thanks - submitted to the Thunderbird addons directory.

**Pull request merged**
