### PR TITLE
changed good.png color from yellow to green (fixes gjedeer/paranoia#6)

### PR DESCRIPTION
**Pull request by bonki**

### CODE REVIEW

**Comment by gjedeer** [comment]
Sorry, this is not going to happen, I like the icons the way they are now.

**Comment by rubo77** [comment]
So why yellow then then?

This would fix it:https://github.com/bonki/paranoia/commit/27008227d872d37ab92536f773f573756c555776

**Comment by gjedeer** [comment]
Because it's a standard emoji color?

Or, more subjectively, because I like it.

**Comment by rubo77** [comment]
Ah now I understand the logic: all smileys are yellow, except angry ones (red) :-)

**Pull request closed without merging**
